[package]
name = "controller_iot"
version = "0.1.0"
authors = ["Jake Mussler <jake.mussler@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
